//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorySession1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCompany
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> TaxpayerIdentificationNumber { get; set; }
        public Nullable<int> RegistrationAccount { get; set; }
        public Nullable<int> BankIdentificationCode { get; set; }
    }
}
