//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorySession1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> IdService { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> IdPetient { get; set; }
        public Nullable<int> IdLaboratoryAssistant { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public string MeanDeviation { get; set; }
        public Nullable<int> NumberProbirki { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
